spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kbank
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/kbank-realm
          jwk-set-uri: http://localhost:8081/realms/kbank-realm/protocol/openid-connect/certs
